# Chat App Service
apiVersion: v1
kind: Service
metadata:
  name: chat-app
  namespace: chat-app
spec:
  selector:
    app: chat-app
  ports:
    - port: 8111
      targetPort: 8111
      name: http
  type: ClusterIP
