# Base Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - mongodb.yaml
  - redis.yaml
  - app.yaml
  - hpa.yaml
